// Quản lý tập trung các hằng số đường dẫn (Route Paths)
export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
  },
  HOME: '/',
  EXPLORE: '/explore',
  POSTS_ALL: '/posts/all',
  REQUESTS: '/requests',
  COMMUNITY: '/community',
  COMMUNITY_CREATE: '/community/create',
  COMMUNITY_DETAIL: '/community/:groupId',
  LEADERBOARD: '/leaderboard',
  POST_CREATE: '/posts/create',
  POST_MENTOR_DETAIL: '/posts/mentor/:id',
  POST_LEARNER_DETAIL: '/posts/learner/:id',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  USER_PROFILE: '/profile/:userId',
  MANAGE: {
    ROOT: '/manage',
    BOOKINGS: '/manage/bookings',
    GROUP_SESSIONS: '/manage/group-sessions',
    SCHEDULE: '/manage/schedule',
    POSTS: '/manage/posts',
    WALLET: '/manage/wallet',
    MESSAGES: '/manage/messages',
    DASHBOARD: '/manage/dashboard',
  },
  ROOMS: {
    ONE_ON_ONE: '/rooms/one-on-one/:bookingId',
    GROUP: '/rooms/group/:roomId',
    LOBBY: '/rooms/group',
  },
  NOT_FOUND: '*',
} as const;
