export const POST_CONFIG = {
  CREDIT_PER_MINUTE: 1,
  DEFAULT_SESSION_DURATION: 60,
  DEFAULT_CREDIT_RATE: 60,
  DEFAULT_PAGE_SIZE: 12,
  SUGGESTIONS_DEBOUNCE_MS: 250,
  MAX_DESCRIPTION_LENGTH: 1000,
  MIN_SEARCH_LENGTH: 2,
};
